# Generated by Django 5.0.4 on 2024-12-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
